### ISSUE TITLE
Changing Hexagrams are missing

### ISSUE THREAD

**Issue by peileppe** [shakeelmohamed/i-ching#1]
Hi Shakeelmohamed,

I was reading your code and noticed the method used by it - only generate one _simple_ Hexagram 
There is also possibility for "changing hexagram" in the case of all coins are heads (_value=6_) or all are tails (_value=9_) 

**This is a great little elegant program as is** - I understand if that wasn't your plan to write this additional part - but needed to make a note about it for people who would read the code and get confused about this missing feature

Have a nice day

**Comment by shakeelmohamed** [comment]
Thanks for the note @peileppe, feel free to make a pull request with the change you're suggesting!
